### ISSUE TITLE
Update `build-and-release-windows.yml` to include text files it depends on

### ISSUE THREAD

**Issue by JamesRobionyRogers** [jesstyrrell/cosc345#32]
To include all required files with your executable in the GitHub release, you'll need to modify your workflow to package these files together. Here's how you can adjust your GitHub Actions script to accomplish this:

1. First, create a directory to collect all the files you want to include in the release.
2. Copy the executable and the required text files into this directory.
3. Zip the directory.
4. Upload the zip file as an artifact.
5. Include the zip file in the release.

Here's the modified version of your workflow:

```yml
name: Build and Release (Windows)

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Release name'
        required: true
        default: 'Automated Release'
      release_description:
        description: 'Release description'
        required: false
        default: 'Automatically generated release'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}

      - name: Run
        run: ${{github.workspace}}/build/Release/PokerGame.exe -ci

      # New step: Create a directory for release files
      - name: Prepare release package
        run: |
          mkdir release_package
          copy ${{github.workspace}}/build/Release/PokerGame.exe release_package\
          copy ${{github.workspace}}\*.txt release_package\

      # New step: Zip the release package
      - name: Zip release package
        run: Compress-Archive -Path release_package\* -DestinationPath PokerGame_release.zip

      # Modified step: Upload the zip file as an artifact
      - name: Upload release package
        uses: actions/upload-artifact@v3
        with:
          name: windows-release-package
          path: PokerGame_release.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Modified step: Download the zip artifact
      - name: Download release package
        uses: actions/download-artifact@v3
        with:
          name: windows-release-package

      - name: Generate and create tag
        id: create_tag
        run: |
          TAG_NAME=v1.0.${{ github.run_number }}
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: List files
        run: ls -R ${{ github.workspace }}

      # Modified step: Upload the zip file to the release
      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ inputs.release_name }}
          body: ${{ inputs.release_description }}
          files: |
            ${{ github.workspace }}/PokerGame_release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

This modified workflow does the following:

1. After building and testing, it creates a `release_package` directory.
2. It copies the executable and all `.txt` files from the workspace root into this directory.
3. It zips the contents of the `release_package` directory into `PokerGame_release.zip`.
4. The zip file is uploaded as an artifact instead of just the executable.
5. In the release job, the zip file is downloaded and then uploaded to the GitHub release.

This approach ensures that all necessary files are included with your executable in a single zip file. Users can download this zip file from the release, extract it, and have all the required files to run your program.

Remember to adjust the `copy ${{github.workspace}}\*.txt release_package\` line if your text files are located in a different directory or if you need to include other file types.
